[target.armv7-unknown-linux-gnueabihf]
image = "rsadsb/ci:0.2.0-armv7-unknown-linux-gnueabihf"

[target.x86_64-unknown-linux-gnu]
image = "rsadsb/ci:0.2.0-x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image = "rsadsb/ci:0.2.0-aarch64-unknown-linux-gnu"
