on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: ci

jobs:
  # build, test all supported targets
  build-test-stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
        toolchain:
          - stable
            # msrv
          - 1.59.0

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.targets }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --locked --workspace --target ${{ matrix.targets }}

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --locked --workspace --target ${{ matrix.targets }}

  # fmt and clippy on nightly builds
  fmt-clippy-nightly:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace -- -D warnings --target
